name: exert
description: "Offline-first exercise discipline app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_auth: ^6.1.1
  firebase_core: ^4.2.0
  cloud_firestore: ^6.0.3
  flutter_svg: ^2.2.0
  path_drawing: ^1.0.1
  flutter_riverpod: ^2.6.1
  go_router: ^16.0.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.5
  intl: ^0.20.2
  table_calendar: ^3.1.3
  xml: ^6.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  isar_generator: ^3.1.0+1
  fake_cloud_firestore: ^4.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: assets/app_icon.png
  remove_alpha_ios: true
  fake_cloud_firestore: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/heatmap/overlay_front.svg
    - assets/heatmap/overlay_back.svg
    - assets/app_icon.png
